language: cpp

env:
  global:
    # URL to .zip source release of ICU
    - ICU_SRC_URL=https://github.com/unicode-org/icu/releases/download/release-67-1/icu4c-67_1-src.zip
    # URL to .zip pre-built release of ICU for Windows x86_64
    - ICU_WIN_URL=https://github.com/unicode-org/icu/releases/download/release-67-1/icu4c-67_1-Win64-MSVC2017.zip
    # Docker run command with arguments common to all manylinux builds
    - DOCKER_RUN="docker run --rm -e CCACHE_DIR=/ccache -e ICU_SRC_URL -v $TRAVIS_BUILD_DIR/ccache:/ccache -v $TRAVIS_BUILD_DIR:/iknow"

jobs:
  include:
    - name: "manylinux2014_aarch64"
      os: linux
      dist: focal
      arch: arm64-graviton2
      virt: lxd
      group: edge
      services: docker
      cache:
        directories: ccache
      script: >-
        $DOCKER_RUN quay.io/pypa/manylinux2014_aarch64 /iknow/travis/build_manylinux.sh &&
        PYTHON=python3 travis/deploy.sh
    - name: "manylinux2014_ppc64le"
      os: linux
      dist: focal
      arch: ppc64le
      services: docker
      cache:
        directories: ccache
      script: >-
        $DOCKER_RUN quay.io/pypa/manylinux2014_ppc64le /iknow/travis/build_manylinux.sh &&
        PYTHON=python3 travis/deploy.sh
    - name: "manylinux2010_x86_64"
      os: linux
      dist: focal
      arch: amd64
      services: docker
      cache:
        directories: ccache
      script: >-
        $DOCKER_RUN quay.io/pypa/manylinux2010_x86_64 /iknow/travis/build_manylinux.sh &&
        PYTHON=python3 travis/deploy.sh
    - name: "Mac OS X 10.9 x86_64"
      os: osx
      osx_image: xcode11.6
      env: HOMEBREW_NO_AUTO_UPDATE=1 PATH="/usr/local/opt/ccache/libexec:$PATH"
      cache: ccache
      install: travis/install_osx.sh
      script: >-
        travis/build_osx.sh &&
        PYTHON=python3.9 travis/deploy.sh
    - name: "Windows x86_64"
      os: windows
      cache:
        directories: buildcache
      install: travis/install_windows.sh
      script: >-
        travis/build_windows.sh &&
        PYTHON="$TRAVIS_BUILD_DIR/python.3.9.0-rc2/tools/python.exe" travis/deploy.sh
