notifications:
  email: false

language: cpp

jobs:
  include:
    - os: linux
      arch: amd64
      sudo: required
      services:
        - docker
      env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
        - TAG=manylinux2010_x86_64
    # - os: linux
    #   arch: amd64
    #   sudo: required
    #   services:
    #     - docker
    #   env:
    #     - DOCKER_IMAGE=quay.io/pypa/manylinux2010_i686
    #     - PRE_CMD=linux32
    #     - TAG=manylinux2010_i686
    # - os: linux
    #   arch: amd64
    #   sudo: required
    #   services:
    #     - docker
    #   env:
    #     - DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
    #     - TAG=manylinux2014_x86_64
    # - os: linux
    #   arch: amd64
    #   sudo: required
    #   services:
    #     - docker
    #   env:
    #     - DOCKER_IMAGE=quay.io/pypa/manylinux2014_i686
    #     - PRE_CMD=linux32
    #     - TAG=manylinux2014_i686
    # - os: linux
    #   arch: arm64
    # - os: linux
    #   arch: ppc64le
    # - os: osx
    # - os: windows

script:
  - docker run --rm -e TRAVIS_COMMIT -v $(pwd):/iknow $DOCKER_IMAGE $PRE_CMD /iknow/travis/build_manylinux.sh $TAG $ICU_URL $PYPI_TOKEN
