language: cpp

env:
  global:
    # Docker run command with arguments common to all manylinux builds
    - DOCKER_RUN="docker run --rm -e CCACHE_DIR=/ccache -e PIP_CACHE_DIR=/pipcache -e ICU_URL -v $HOME/ccache:/ccache -v $HOME/pipcache:/pipcache -v $TRAVIS_BUILD_DIR:/iknow"
    # directory where ICU is installed on host
    - ICUDIR="$TRAVIS_BUILD_DIR/thirdparty/icu"

before_install: . travis/dependencies.sh

jobs:
  include:
    - name: "manylinux2014_aarch64"
      os: linux
      dist: focal
      arch: arm64-graviton2
      virt: lxd
      group: edge
      services: docker
      cache:
        directories:
          - $ICUDIR
          - $HOME/ccache
          - $HOME/pipcache  # pip cache for container
          - $HOME/.cache/pip  # pip cache for host
      script: >-
        $DOCKER_RUN quay.io/pypa/manylinux2014_aarch64 /iknow/travis/build_manylinux.sh &&
        travis/deploy.sh
    - name: "manylinux2014_ppc64le"
      os: linux
      dist: focal
      arch: ppc64le
      services: docker
      cache:
        directories:
          - $ICUDIR
          - $HOME/ccache
          - $HOME/pipcache
          - $HOME/.cache/pip
      script: >-
        $DOCKER_RUN quay.io/pypa/manylinux2014_ppc64le /iknow/travis/build_manylinux.sh &&
        travis/deploy.sh
    - name: "manylinux2010_x86_64"
      os: linux
      dist: focal
      arch: amd64
      services: docker
      cache:
        directories:
          - $ICUDIR
          - $HOME/ccache
          - $HOME/pipcache
          - $HOME/.cache/pip
      script: >-
        $DOCKER_RUN quay.io/pypa/manylinux2010_x86_64 /iknow/travis/build_manylinux.sh &&
        travis/deploy.sh
    - name: "Mac OS X 10.9 x86_64"
      os: osx
      osx_image: xcode11.7
      env: >-
        HOMEBREW_NO_AUTO_UPDATE=1
        MACOSX_DEPLOYMENT_TARGET=10.9
        PATH="/usr/local/opt/ccache/libexec:$PATH"
        CCACHE_DIR="$HOME/ccache"
        PIP_CACHE_DIR="$HOME/pipcache"
        PYINSTALL_DIR="$HOME/.pyenv/versions"
      cache:
        directories:
          - $ICUDIR
          - $CCACHE_DIR
          - $PIP_CACHE_DIR
          - $PYINSTALL_DIR
      install:
        - eval "$(pyenv init -)"
        - travis/install_osx.sh
      script: >-
        travis/build_osx.sh &&
        travis/deploy.sh
    - name: "Windows x86_64"
      os: windows
      env: >-
        BUILDCACHE_DIR="$HOME/buildcache"
        PIP_CACHE_DIR="$HOME/pipcache"
        PYINSTALL_DIR="$HOME/python"
      cache:
        directories:
          - $ICUDIR
          - $BUILDCACHE_DIR
          - $PIP_CACHE_DIR
          - $PYINSTALL_DIR
      install: travis/install_windows.sh
      script: >-
        travis/build_windows.sh &&
        travis/deploy.sh
