notifications:
  email: false

language: cpp

jobs:
  include:
    # - os: linux
    #   arch: amd64
    #   services:
    #     - docker
    #   env:
    #     - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
    #     - TAG=manylinux2010_x86_64
    # - os: linux
    #   arch: amd64
    #   services:
    #     - docker
    #   env:
    #     - DOCKER_IMAGE=quay.io/pypa/manylinux2010_i686
    #     - PRE_CMD=linux32
    #     - TAG=manylinux2010_i686
    # - os: linux
    #   arch: amd64
    #   services:
    #     - docker
    #   env:
    #     - DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
    #     - TAG=manylinux2014_x86_64
    # - os: linux
    #   arch: amd64
    #   services:
    #     - docker
    #   env:
    #     - DOCKER_IMAGE=quay.io/pypa/manylinux2014_i686
    #     - PRE_CMD=linux32
    #     - TAG=manylinux2014_i686
    - os: linux
      arch: arm64
      services:
        - docker
      env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64
        - TAG=manylinux2014_aarch64
    # - os: linux
    #   arch: ppc64le
    #   sudo: required
    #   services:
    #     - docker
    #   env:
    #     - DOCKER_IMAGE=quay.io/pypa/manylinux2014_ppc64le
    #     - TAG=manylinux2014_ppc64le
    - os: osx
      install:
        - echo "install step for Mac OS run"
    # - os: windows

script:
  - travis/build.sh
